In [13]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import datasets, svm, metrics

digits = datasets.load_digits()

n_samples = len(digits.images)

# 1797*8*8 => 1797*64*1
data = digits.images.reshape(n_samples, -1)

# SVC分类器
classifier = svm.SVC(gamma=0.001)

# 用前半部分做训练集
classifier.fit(data[:n_samples / 2], digits.target[:n_samples / 2])

expected = digits.target[n_samples / 2:]

# 用后半部分做测试集
predicted = classifier.predict(data[n_samples / 2:])

# 测试误差
print metrics.confusion_matrix(expected, predicted)

[[87  0  0  0  1  0  0  0  0  0]
 [ 0 88  1  0  0  0  0  0  1  1]
 [ 0  0 85  1  0  0  0  0  0  0]
 [ 0  0  0 79  0  3  0  4  5  0]
 [ 0  0  0  0 88  0  0  0  0  4]
 [ 0  0  0  0  0 88  1  0  0  2]
 [ 0  1  0  0  0  0 90  0  0  0]
 [ 0  0  0  0  0  1  0 88  0  0]
 [ 0  0  0  0  0  0  0  0 88  0]
 [ 0  0  0  1  0  1  0  0  0 90]]
